ALTER DATABASE ShopDB
ADD FILEGROUP FG_ShopCatalog;

ALTER DATABASE ShopDB
ADD FILEGROUP FG_ShopSales;

ALTER DATABASE ShopDB
ADD FILE
(
    NAME = ShopCatalog,
    FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL17.SQLEXPRESS\MSSQL\DATA\ShopCatalog.ndf',
    SIZE = 10MB,
    FILEGROWTH = 5MB
)
TO FILEGROUP FG_ShopCatalog;
GO

ALTER DATABASE ShopDB
ADD FILE
(
    NAME = ShopSales,
    FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL17.SQLEXPRESS\MSSQL\DATA\ShopSales.ndf',
    SIZE = 10MB,
    FILEGROWTH = 5MB
)
TO FILEGROUP FG_ShopSales;
GO